apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: f-cluster
  region: ap-south-1

fargateProfiles:
  - name: fargate-default
    selectors:
     - namespace: kube-system
     - namespace: default